### ISSUE TITLE
purge_cache is broken

### ISSUE THREAD

**Issue by knu** [ninech/cloudflair#10]
The endpoint `/zones/:zone_id/purge_cache` only accepts `POST`:
https://api.cloudflare.com/#zone-purge-all-files

But this library tries to request using the `DELETE` method:
https://github.com/ninech/cloudflair/blob/3c50778dae8f4ba73eacb8aad13f66defdc2a8f8/lib/cloudflair/api/zone/purge_cache.rb#L16
https://github.com/ninech/cloudflair/blob/3c50778dae8f4ba73eacb8aad13f66defdc2a8f8/lib/cloudflair/api/zone/purge_cache.rb#L26

**Comment by thde** [comment]
Fixed by #12
